### ISSUE TITLE
Non-approved use cases are published to website

### ISSUE THREAD

**Issue by tschady** [FDC3/use-cases#2]
https://fdc3-use-cases.finos.org/2018/11/07/006-dynamic-discovery-in-chat.html

https://fdc3-use-cases.finos.org/2018/11/07/007-platform-agnostic-interop-api.html

**Comment by tschady** [comment]
This is my comment!

**Comment by tschady** [comment]
@saori-tr check this out please

**Comment by saori-tr** [comment]
Closing as these have been removed on the new FDC3/FDC3 repo/website.
