### ISSUE TITLE
Approved Use cases have unreadable contrast in status bar

### ISSUE THREAD

**Issue by tschady** [FDC3/use-cases#3]
![image](https://user-images.githubusercontent.com/1934009/51695969-f4f38b80-1fc9-11e9-9e37-3496b91856f7.png)

More contrast needed.  Alternatively, if only Approved use cases are published, this status may be removed.  See #2 

Highlighting the bar shows the included text:
![image](https://user-images.githubusercontent.com/1934009/51696044-279d8400-1fca-11e9-87fe-97085c800e5d.png)

**Comment by saori-tr** [comment]
No longer relevant in the new site/repo since only Accepted use cases will make it to the website.  Closing.
