### ISSUE TITLE
enable CODEOWNER restrictions in repo settings

### ISSUE THREAD

**Issue by tschady** [FDC3/use-cases#8]
see #5 

Please update settings to protect master with CODEOWNER approval.

![image](https://user-images.githubusercontent.com/1934009/52420755-4b77c400-2ab8-11e9-83ee-81034168b5e9.png)

**Comment by tschady** [comment]
@finos-admin ^

**Comment by saori-tr** [comment]
@tschady please open this issue again (as needed) on the new FDC3/FDC3 repo.  I am closing this one as this repo will be archived.
